import herbsImg from "@/assets/cat-herbs.jpg";
import flowersImg from "@/assets/cat-flowers.jpg";
import tincturesImg from "@/assets/cat-tinctures.jpg";
import teasImg from "@/assets/cat-teas.jpg";
import oilsImg from "@/assets/cat-oils.jpg";
import kitsImg from "@/assets/cat-kits.jpg";

export type Category = {
  slug: string;
  name: string;
  blurb: string;
  image: string;
};

export const categories: Category[] = [
  {
    slug: "herbs",
    name: "Dried Herbs",
    blurb: "Sun-dried leaves and roots harvested at peak vitality.",
    image: herbsImg,
  },
  {
    slug: "flowers",
    name: "Wild Flowers",
    blurb: "Pressed petals and full blooms for teas, baths, and rituals.",
    image: flowersImg,
  },
  {
    slug: "tinctures",
    name: "Tinctures & Elixirs",
    blurb: "Small-batch potions, slow-steeped in pure spirits.",
    image: tincturesImg,
  },
  {
    slug: "teas",
    name: "Herbal Teas",
    blurb: "Hand-blended brews for rest, focus, and warmth.",
    image: teasImg,
  },
  {
    slug: "oils",
    name: "Essential Oils",
    blurb: "Cold-pressed aromatics in apothecary amber glass.",
    image: oilsImg,
  },
  {
    slug: "kits",
    name: "Apothecary Kits",
    blurb: "Adventurer's chests stocked for any quest.",
    image: kitsImg,
  },
  {
    slug: "books",
    name: "PDF Field Guides",
    blurb: "Digital ingredient books with preparation notes and citations.",
    image: kitsImg,
  },
];

export type Product = {
  slug: string;
  name: string;
  category: string;
  type: "ingredient" | "blend" | "kit" | "book";
  price: number;
  short: string;
  description: string;
  uses: string[];
  ingredients: string[];
  image: string;
  badge?: string;
  format?: string;
  proofNotes?: string[];
};

export const products: Product[] = [
  {
    slug: "mugwort-dream-herb",
    name: "Mugwort Dream Herb",
    category: "herbs",
    type: "ingredient",
    price: 12,
    short: "Aromatic dried mugwort for dream and altar work.",
    description:
      "Carefully dried mugwort leaf for non-ingestible dream sachets, altar bundles, and ingredient study. Includes clear safety guidance for respectful home practice.",
    uses: ["Dream sachets", "Altar work", "Ingredient study"],
    ingredients: ["Artemisia vulgaris leaf"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "dragons-blood-resin",
    name: "Dragon's Blood Resin",
    category: "herbs",
    type: "ingredient",
    price: 18,
    short: "Deep red resin traditionally used in protective incense.",
    description:
      "Small resin pieces selected for incense and ritual study, with notes on ventilation, fire safety, and the varied plants sold under the dragon's blood name.",
    uses: ["Incense", "Protection work", "Cleansing"],
    ingredients: ["Dragon's blood resin"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "rose-petals",
    name: "Dried Rose Petals",
    category: "flowers",
    type: "ingredient",
    price: 11,
    short: "Fragrant petals for baths, teas, and heart-centered rituals.",
    description:
      "Food-grade dried rose petals with a soft floral aroma, packed for tea blending, botanical baths, and devotional craft.",
    uses: ["Tea blends", "Baths", "Floral water"],
    ingredients: ["Rosa species petals"],
    image: flowersImg,
    badge: "Book of Roots",
  },
  {
    slug: "rue-protection-herb",
    name: "Rue Protection Herb",
    category: "herbs",
    type: "ingredient",
    price: 10,
    short: "A potent aromatic herb for protected altar use.",
    description:
      "Dried rue intended for symbolic bundles and altar work only. The package foregrounds pregnancy, skin, and ingestion cautions.",
    uses: ["Altar bundles", "Protective craft", "Ingredient study"],
    ingredients: ["Ruta graveolens herb"],
    image: herbsImg,
    badge: "Handle with care",
  },
  {
    slug: "frankincense-resin",
    name: "Frankincense Resin Tears",
    category: "herbs",
    type: "ingredient",
    price: 16,
    short: "Bright Boswellia resin for incense and contemplation.",
    description:
      "Responsibly sourced frankincense tears for prayer, meditation, and aromatic study, accompanied by safe-burning instructions.",
    uses: ["Incense", "Meditation", "Devotional practice"],
    ingredients: ["Boswellia resin"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "valerian-root",
    name: "Cut Valerian Root",
    category: "herbs",
    type: "ingredient",
    price: 14,
    short: "Earthy cut root for traditional evening preparations.",
    description:
      "Cut and sifted valerian root with preparation notes and cautions around sedatives, alcohol, pregnancy, and persistent sleep concerns.",
    uses: ["Evening infusion", "Ingredient study"],
    ingredients: ["Valeriana officinalis root"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "john-the-conqueror-root",
    name: "John the Conqueror Root",
    category: "herbs",
    type: "ingredient",
    price: 21,
    short: "A whole root honored in Black American Hoodoo tradition.",
    description:
      "A whole High John root offered with historical context and guidance that centers reputable Hoodoo educators and lineage-specific practice.",
    uses: ["Mojo bag", "Altar work", "Cultural study"],
    ingredients: ["Ipomoea jalapa root"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "ashwagandha-root",
    name: "Ashwagandha Root Powder",
    category: "herbs",
    type: "ingredient",
    price: 17,
    short: "Ground Ayurvedic root for warm, grounding preparations.",
    description:
      "Fine ashwagandha root powder with preparation ideas and prominent guidance for thyroid, autoimmune, pregnancy, and medication considerations.",
    uses: ["Warm milk blend", "Ingredient study"],
    ingredients: ["Withania somnifera root powder"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "blue-lotus-flower",
    name: "Blue Lotus Flowers",
    category: "flowers",
    type: "ingredient",
    price: 22,
    short: "Dried blue water lily flowers for contemplative practice.",
    description:
      "Verified dried blue water lily flowers presented with a clear distinction between ancient Egyptian evidence and contemporary spiritual use.",
    uses: ["Meditation bowl", "Altar work", "Ingredient study"],
    ingredients: ["Nymphaea caerulea flowers"],
    image: flowersImg,
    badge: "Book of Roots",
  },
  {
    slug: "palo-santo-wood",
    name: "Ethically Sourced Palo Santo",
    category: "herbs",
    type: "ingredient",
    price: 15,
    short: "Naturally fallen aromatic wood with sourcing notes.",
    description:
      "Traceable palo santo wood sourced from naturally fallen material, with species, origin, and harvest documentation included.",
    uses: ["Aromatic altar work", "Cleansing", "Ingredient study"],
    ingredients: ["Bursera graveolens wood"],
    image: herbsImg,
    badge: "Sourcing verified",
  },
  {
    slug: "calendula-flowers",
    name: "Calendula Flowers",
    category: "flowers",
    type: "ingredient",
    price: 12,
    short: "Golden whole flowers for oil infusions and botanical craft.",
    description:
      "Fully dried calendula flowers for skin-safe oil infusions, bath blends, and cheerful seasonal craft.",
    uses: ["Oil infusion", "Bath blend", "Botanical craft"],
    ingredients: ["Calendula officinalis flowers"],
    image: flowersImg,
    badge: "Book of Roots",
  },
  {
    slug: "black-cohosh-root",
    name: "Black Cohosh Root",
    category: "herbs",
    type: "ingredient",
    price: 19,
    short: "Practitioner-guided root with detailed safety notes.",
    description:
      "Cut black cohosh root sold for informed ingredient study and practitioner-guided use, with sourcing and safety documentation.",
    uses: ["Ingredient study", "Practitioner-guided preparation"],
    ingredients: ["Actaea racemosa root"],
    image: herbsImg,
    badge: "Guided use",
  },
  {
    slug: "deku-leaf-bundle",
    name: "Deku Leaf Bundle",
    category: "herbs",
    type: "ingredient",
    price: 14,
    short: "Energizing green leaves, gathered at dawn.",
    description:
      "A hand-tied bundle of sun-dried deku leaves, prized for centuries by woodland herbalists. Steep, smolder, or steep into a tonic.",
    uses: ["Smoke cleansing", "Energizing tea", "Salve base"],
    ingredients: ["Wildcrafted deku leaf"],
    image: herbsImg,
    badge: "Bestseller",
    proofNotes: ["Batch notes include harvest date, drying method, and supplier lot."],
  },
  {
    slug: "korok-mint",
    name: "Korok Mint Sprigs",
    category: "herbs",
    type: "ingredient",
    price: 9,
    short: "Bright, cooling, and a little mischievous.",
    description:
      "Refreshing mint with a hint of forest pine. Excellent for after-meal teas or muddled into spring water.",
    uses: ["Digestive tea", "Cooling balm"],
    ingredients: ["Organic korok mint"],
    image: herbsImg,
  },
  {
    slug: "moringa-leaf-powder",
    name: "Moringa Leaf Powder",
    category: "herbs",
    type: "ingredient",
    price: 15,
    short: "A mineral-rich green powder for daily blends.",
    description:
      "Fine-ground moringa leaf with a grassy, earthy profile. Blend into smoothies, capsules, soups, or tea mixes for everyday nourishment.",
    uses: ["Smoothies", "Capsules", "Green tea blends"],
    ingredients: ["Moringa oleifera leaf powder"],
    image: herbsImg,
    badge: "New",
    proofNotes: [
      "Research notes track traditional food uses and published nutrient profiles.",
      "Sourced with certificate of analysis before sale.",
    ],
  },
  {
    slug: "hibiscus-calypso-calyx",
    name: "Hibiscus Calypso Calyx",
    category: "flowers",
    type: "ingredient",
    price: 12,
    short: "Tart crimson petals for tea, syrups, and color.",
    description:
      "Deep red hibiscus calyces with bright berry-like acidity. A beautiful anchor for iced teas, oxymels, syrups, and botanical mocktails.",
    uses: ["Iced tea", "Syrup", "Oxymel", "Natural color"],
    ingredients: ["Hibiscus sabdariffa calyces"],
    image: flowersImg,
    badge: "Caribbean shelf",
    proofNotes: ["Reference notes include food history, acidity, and preparation guidance."],
  },
  {
    slug: "silent-princess",
    name: "Silent Princess Petals",
    category: "flowers",
    type: "ingredient",
    price: 24,
    short: "Rare blue petals, pressed and preserved.",
    description:
      "These famously elusive blossoms are pressed within hours of harvest to retain their delicate sapphire color and faintly floral aroma.",
    uses: ["Ceremonial baths", "Tea blend top note", "Floral water"],
    ingredients: ["Silent princess petals"],
    image: flowersImg,
    badge: "Rare",
  },
  {
    slug: "hyrule-wildflower-mix",
    name: "Hyrule Wildflower Mix",
    category: "flowers",
    type: "blend",
    price: 16,
    short: "A meadow in a jar.",
    description:
      "A vivid medley of pressed wildflowers, chamomile, cornflower, marigold, and rose, blended for color and gentle fragrance.",
    uses: ["Bath soak", "Tea garnish", "Potpourri"],
    ingredients: ["Chamomile", "Cornflower", "Calendula", "Rose petals"],
    image: flowersImg,
  },
  {
    slug: "elixir-of-stamina",
    name: "Elixir of Stamina",
    category: "tinctures",
    type: "blend",
    price: 32,
    short: "A slow-steeped green tonic for long roads.",
    description:
      "Our flagship tincture, drawn from rhodiola, ginseng, and forest-foraged adaptogens. A few drops under the tongue before any quest.",
    uses: ["Energy support", "Endurance"],
    ingredients: ["Rhodiola", "Korean ginseng", "Schisandra", "Cane spirit"],
    image: tincturesImg,
    badge: "Bestseller",
  },
  {
    slug: "elixir-of-courage",
    name: "Elixir of Courage",
    category: "tinctures",
    type: "blend",
    price: 32,
    short: "Warming red tincture for steady nerves.",
    description:
      "Hawthorn and motherwort steeped with rose hip and a whisper of cayenne, a heart-strengthening classic.",
    uses: ["Heart support", "Calm focus"],
    ingredients: ["Hawthorn berry", "Motherwort", "Rose hip", "Cane spirit"],
    image: tincturesImg,
  },
  {
    slug: "elixir-of-wisdom",
    name: "Elixir of Wisdom",
    category: "tinctures",
    type: "blend",
    price: 32,
    short: "A clarifying blue elixir for thinkers.",
    description:
      "Bacopa, gotu kola, and butterfly pea slow-extracted into a midnight-blue tincture for memory and clarity.",
    uses: ["Mental clarity", "Focus"],
    ingredients: ["Bacopa", "Gotu kola", "Butterfly pea", "Cane spirit"],
    image: tincturesImg,
  },
  {
    slug: "lullaby-tea-blend",
    name: "Lullaby Tea Blend",
    category: "teas",
    type: "blend",
    price: 18,
    short: "Soft notes of chamomile, lavender, and oat.",
    description:
      "A bedtime ritual in a tin. Loose-leaf, hand-blended in small batches, for the quietest hour of the night.",
    uses: ["Sleep", "Wind-down ritual"],
    ingredients: ["Chamomile", "Lavender", "Oat straw", "Passionflower"],
    image: teasImg,
    badge: "Bestseller",
  },
  {
    slug: "lon-lon-chai",
    name: "Lon Lon Chai",
    category: "teas",
    type: "blend",
    price: 16,
    short: "Spiced black tea fit for ranch hands.",
    description:
      "Robust Assam steeped with cinnamon, cardamom, clove, and a touch of vanilla. Drinks beautifully with milk.",
    uses: ["Morning tea", "Cozy afternoons"],
    ingredients: ["Assam black tea", "Cinnamon", "Cardamom", "Clove", "Vanilla"],
    image: teasImg,
  },
  {
    slug: "soursop-leaf-tea",
    name: "Soursop Leaf Tea",
    category: "teas",
    type: "ingredient",
    price: 14,
    short: "Whole leaves for a gentle island steep.",
    description:
      "Carefully dried soursop leaves prepared for simple infusions. Earthy, mellow, and rooted in Caribbean home traditions.",
    uses: ["Simple infusion", "Evening tea", "Ingredient study"],
    ingredients: ["Annona muricata leaf"],
    image: teasImg,
    badge: "New",
    proofNotes: [
      "Educational notes separate traditional use from medical claims.",
      "Future book download will collect citations and preparation history.",
    ],
  },
  {
    slug: "ginger-root",
    name: "Cut Ginger Root",
    category: "herbs",
    type: "ingredient",
    price: 10,
    short: "Warming cut root for teas, syrups, and kitchen blends.",
    description:
      "Dried ginger root pieces for food-first preparations, with clear cautions for medication interactions and sensitive digestion.",
    uses: ["Tea", "Syrup", "Digestive kitchen blends"],
    ingredients: ["Zingiber officinale root"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "turmeric-root-powder",
    name: "Turmeric Root Powder",
    category: "herbs",
    type: "ingredient",
    price: 13,
    short: "Golden rhizome powder for warm milk, food, and study.",
    description:
      "Fine turmeric powder for culinary preparations and ingredient education, packaged with stain, gallbladder, and blood-thinner cautions.",
    uses: ["Golden milk", "Food blends", "Ingredient study"],
    ingredients: ["Curcuma longa rhizome powder"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "tulsi-holy-basil",
    name: "Tulsi Holy Basil",
    category: "teas",
    type: "ingredient",
    price: 13,
    short: "A fragrant Ayurvedic leaf for devotional tea rituals.",
    description:
      "Dried tulsi leaf for simple infusions, with notes on Indian cultural context, medication cautions, and respectful everyday use.",
    uses: ["Tea", "Devotional practice", "Ingredient study"],
    ingredients: ["Ocimum tenuiflorum leaf"],
    image: teasImg,
    badge: "Book of Roots",
  },
  {
    slug: "elderberry-whole-berries",
    name: "Whole Elderberries",
    category: "herbs",
    type: "ingredient",
    price: 15,
    short: "Dried berries for cooked syrups and seasonal pantry craft.",
    description:
      "Whole dried elderberries intended for properly cooked preparations only, with strong raw-plant safety notes and straining guidance.",
    uses: ["Cooked syrup", "Seasonal pantry", "Ingredient study"],
    ingredients: ["Sambucus nigra berries"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "mullein-leaf",
    name: "Mullein Leaf",
    category: "herbs",
    type: "ingredient",
    price: 12,
    short: "Soft dried leaf for mountain-style tea and steam study.",
    description:
      "Dried mullein leaf with fine-straining instructions, steam safety notes, and Appalachian folk context.",
    uses: ["Steam bowl", "Tea study", "Folk medicine notes"],
    ingredients: ["Verbascum thapsus leaf"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "sassafras-file-leaf",
    name: "Sassafras File Leaf",
    category: "herbs",
    type: "ingredient",
    price: 11,
    short: "Culinary file-style leaf powder for Gulf South flavor notes.",
    description:
      "A food-focused sassafras leaf product for seasoning and cultural study, clearly separated from root bark preparations.",
    uses: ["Seasoning", "Cajun foodways", "Ingredient study"],
    ingredients: ["Sassafras albidum leaf"],
    image: herbsImg,
    badge: "Book of Roots",
  },
  {
    slug: "lavender-oil",
    name: "Field Lavender Oil",
    category: "oils",
    type: "ingredient",
    price: 22,
    short: "Steam-distilled French lavender.",
    description:
      "Single-origin Provence lavender, gently distilled and bottled in amber glass to preserve its calming aromatic profile.",
    uses: ["Aromatherapy", "Pillow mist base", "Massage blend"],
    ingredients: ["Lavandula angustifolia essential oil"],
    image: oilsImg,
  },
  {
    slug: "cedarwood-oil",
    name: "Lost Woods Cedarwood",
    category: "oils",
    type: "ingredient",
    price: 20,
    short: "Grounding, woody, ancient.",
    description:
      "Atlas cedarwood oil with a deep, balsamic aroma. Diffuse for focus or blend into beard and skin oils.",
    uses: ["Diffuser", "Grounding", "Skin oil"],
    ingredients: ["Cedrus atlantica essential oil"],
    image: oilsImg,
  },
  {
    slug: "traveler-apothecary-kit",
    name: "Traveler's Apothecary Kit",
    category: "kits",
    type: "kit",
    price: 84,
    short: "Everything an adventurer needs in one chest.",
    description:
      "A wooden chest with five tinctures, three teas, a mortar and pestle, and a hand-bound guide of remedies. The perfect gift for the curious herbalist.",
    uses: ["Gift", "Starter set", "Travel"],
    ingredients: ["Assorted tinctures, teas, and tools"],
    image: kitsImg,
    badge: "Gift",
  },
  {
    slug: "healers-starter-kit",
    name: "Healer's Starter Kit",
    category: "kits",
    type: "kit",
    price: 58,
    short: "A first apothecary for new herbalists.",
    description:
      "Includes our top three teas, two essential oils, a recipe scroll, and a small mortar and pestle.",
    uses: ["Beginner", "Gift"],
    ingredients: ["Assorted teas, oils, and tools"],
    image: kitsImg,
  },
  {
    slug: "hibiscus-field-guide-pdf",
    name: "Hibiscus Field Guide PDF",
    category: "books",
    type: "book",
    price: 11,
    short: "A printable study guide for hibiscus history, prep, and evidence.",
    description:
      "A digital field guide for learning hibiscus as food, color, tea, and cultural ingredient. Built for curious herbalists who want the magic and the receipts in one place.",
    uses: ["Ingredient study", "Kitchen reference", "Printable notes"],
    ingredients: ["PDF download", "Preparation charts", "Research bibliography"],
    image: kitsImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: [
      "Designed for Cloudflare R2 protected delivery after checkout.",
      "Includes space for citations, source notes, and batch references.",
    ],
  },
  {
    slug: "island-green-remedies-pdf",
    name: "Island Green Remedies PDF",
    category: "books",
    type: "book",
    price: 13,
    short: "A Caribbean-inspired guide to greens, roots, and flower remedies.",
    description:
      "A digital book concept honoring island plant knowledge with modern citation notes, preparation boundaries, and ingredient profiles.",
    uses: ["Ingredient education", "Recipe planning", "Subscriber release"],
    ingredients: ["PDF download", "Ingredient profiles", "Evidence notes"],
    image: kitsImg,
    badge: "Coming soon",
    format: "PDF download",
    proofNotes: ["Prepared as a sellable digital product once rights and references are verified."],
  },
  {
    slug: "chinese-traditional-medicine-pdf",
    name: "Chinese Traditional Medicine PDF",
    category: "books",
    type: "book",
    price: 18,
    short: "A cultural field guide to TCM herbs, formula thinking, and preparation cautions.",
    description:
      "A downloadable booklet introducing Chinese Traditional Medicine through origin, key herbs, kitchen-safe examples, proof notes, and respectful boundaries.",
    uses: ["Chinese tradition", "Digestion", "Immunity", "Teas"],
    ingredients: ["PDF download", "First-page preview", "Evidence notes"],
    image: teasImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Full content unlocks after Stripe checkout and later protected delivery setup."],
  },
  {
    slug: "cajun-folk-remedies-pdf",
    name: "Cajun Folk Remedies PDF",
    category: "books",
    type: "book",
    price: 16,
    short: "Bayou household remedy notes organized with safety, folklore, and plant ID care.",
    description:
      "A digital guide to Cajun and Louisiana folk remedy context, featuring kitchen remedies, steam bowls, teas, and clear non-medical education language.",
    uses: ["Cajun tradition", "Digestion", "Skin care", "Teas"],
    ingredients: ["PDF download", "First-page preview", "Recipe archive"],
    image: herbsImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Includes space for oral-history notes and folklife references."],
  },
  {
    slug: "african-herbalism-pdf",
    name: "African Herbalism PDF",
    category: "books",
    type: "book",
    price: 18,
    short: "A region-aware introduction to African food herbs, tree medicines, and ethics.",
    description:
      "An educational booklet that avoids treating Africa as one tradition and instead frames herbs through regional specificity, foodways, and source notes.",
    uses: ["African tradition", "Nutrition", "Skin care", "Roots"],
    ingredients: ["PDF download", "Ingredient profiles", "Evidence notes"],
    image: herbsImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Prepared for future citation expansion and protected delivery."],
  },
  {
    slug: "wiccan-earth-based-healing-pdf",
    name: "Wiccan Earth-Based Healing PDF",
    category: "books",
    type: "book",
    price: 15,
    short: "Herbal correspondences, ritual safety, and earth-based recipe notes.",
    description:
      "A digital ritual field guide for Wiccan and earth-based botanical work with smoke-free options, plant cautions, and seasonal recipe pages.",
    uses: ["Wiccan tradition", "Protection", "Sleep", "Flowers"],
    ingredients: ["PDF download", "Ritual notes", "Recipe archive"],
    image: flowersImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Separates spiritual practice from medical claims."],
  },
  {
    slug: "ayurvedic-indian-medicine-pdf",
    name: "Ayurvedic Indian Medicine PDF",
    category: "books",
    type: "book",
    price: 18,
    short: "Dosha, digestion, rasayana herbs, and kitchen preparations in one booklet.",
    description:
      "A cultural guide to Ayurvedic herb education, with practitioner boundaries, warm preparation ideas, and careful notes for medications and pregnancy.",
    uses: ["Ayurvedic tradition", "Sleep", "Digestion", "Oils"],
    ingredients: ["PDF download", "Preparation charts", "Evidence notes"],
    image: oilsImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Designed as educational content, not individualized Ayurvedic care."],
  },
  {
    slug: "native-american-plant-medicine-pdf",
    name: "Native American Plant Medicine PDF",
    category: "books",
    type: "book",
    price: 18,
    short: "An ethics-first guide to Native plant medicine history and sourcing boundaries.",
    description:
      "A respectful overview centered on sovereignty, closed knowledge, plant conservation, and only publicly shared educational material.",
    uses: ["Native American tradition", "Ethical sourcing", "Roots", "Teas"],
    ingredients: ["PDF download", "Ethics notes", "First-page preview"],
    image: kitsImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Content is intentionally limited to public, permission-safe education."],
  },
  {
    slug: "caribbean-rastafarian-herbalism-pdf",
    name: "Caribbean Rastafarian Herbalism PDF",
    category: "books",
    type: "book",
    price: 17,
    short: "Bush tea, ital living, bitters, roots tonics, and island plant notes.",
    description:
      "A digital booklet for Caribbean and Rastafarian herbal education, featuring hibiscus, soursop, moringa, bitters, and safety boundaries.",
    uses: ["Caribbean tradition", "Digestion", "Immunity", "Teas"],
    ingredients: ["PDF download", "Recipe archive", "Ingredient profiles"],
    image: teasImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Documents traditional use without disease-treatment claims."],
  },
  {
    slug: "appalachian-folk-medicine-pdf",
    name: "Appalachian Folk Medicine PDF",
    category: "books",
    type: "book",
    price: 16,
    short: "Mountain remedy traditions, harvest ethics, teas, poultices, and garden medicine.",
    description:
      "A digital Appalachian folk medicine booklet covering home remedy history, plant identification caution, conservation, and preparation notes.",
    uses: ["Appalachian tradition", "Sleep", "Pain relief", "Roots"],
    ingredients: ["PDF download", "First-page preview", "Folklife notes"],
    image: herbsImg,
    badge: "Digital",
    format: "PDF download",
    proofNotes: ["Built for future bibliography and protected PDF delivery."],
  },
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
export const getCategory = (slug: string) => categories.find((c) => c.slug === slug);
