create table if not exists public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  source text not null default 'site',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.subscribers enable row level security;

create policy "Service role can manage subscribers"
on public.subscribers
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  category text not null,
  type text not null check (type in ('ingredient', 'blend', 'kit', 'book')),
  price_cents integer not null,
  short text not null,
  description text not null,
  image_url text,
  storage_object_key text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products enable row level security;

create policy "Published products are public"
on public.products
for select
using (status = 'active');

create policy "Service role can manage products"
on public.products
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.product_notes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  note_type text not null default 'proof',
  body text not null,
  citation_url text,
  sort_order integer not null default 0
);

alter table public.product_notes enable row level security;

create policy "Notes for active products are public"
on public.product_notes
for select
using (
  exists (
    select 1
    from public.products
    where products.id = product_notes.product_id
    and products.status = 'active'
  )
);

create policy "Service role can manage product notes"
on public.product_notes
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  user_email text,
  stripe_checkout_session_id text unique,
  status text not null default 'pending',
  subtotal_cents integer not null default 0,
  total_cents integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;

create policy "Users can read their own orders"
on public.orders
for select
using (auth.uid() = user_id);

create policy "Service role can manage orders"
on public.orders
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_slug text not null,
  quantity integer not null,
  unit_price_cents integer not null
);

alter table public.order_items enable row level security;

create policy "Users can read their own order items"
on public.order_items
for select
using (
  exists (
    select 1
    from public.orders
    where orders.id = order_items.order_id
    and orders.user_id = auth.uid()
  )
);

create policy "Service role can manage order items"
on public.order_items
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

insert into public.products (slug, name, category, type, price_cents, short, description, status)
values
  ('mugwort-dream-herb', 'Mugwort Dream Herb', 'herbs', 'ingredient', 1200, 'Aromatic dried mugwort for dream and altar work.', 'Carefully dried mugwort leaf for non-ingestible dream sachets, altar bundles, and ingredient study.', 'active'),
  ('dragons-blood-resin', 'Dragon''s Blood Resin', 'herbs', 'ingredient', 1800, 'Deep red resin traditionally used in protective incense.', 'Small resin pieces selected for incense and ritual study with fire-safety notes.', 'active'),
  ('rose-petals', 'Dried Rose Petals', 'flowers', 'ingredient', 1100, 'Fragrant petals for baths, teas, and heart-centered rituals.', 'Food-grade dried rose petals packed for tea blending, botanical baths, and devotional craft.', 'active'),
  ('rue-protection-herb', 'Rue Protection Herb', 'herbs', 'ingredient', 1000, 'A potent aromatic herb for protected altar use.', 'Dried rue intended for symbolic bundles and altar work only, with prominent safety guidance.', 'active'),
  ('frankincense-resin', 'Frankincense Resin Tears', 'herbs', 'ingredient', 1600, 'Bright Boswellia resin for incense and contemplation.', 'Responsibly sourced frankincense tears for prayer, meditation, and aromatic study.', 'active'),
  ('valerian-root', 'Cut Valerian Root', 'herbs', 'ingredient', 1400, 'Earthy cut root for traditional evening preparations.', 'Cut and sifted valerian root with preparation and interaction notes.', 'active'),
  ('john-the-conqueror-root', 'John the Conqueror Root', 'herbs', 'ingredient', 2100, 'A whole root honored in Black American Hoodoo tradition.', 'A whole High John root offered with historical and lineage-specific context.', 'active'),
  ('ashwagandha-root', 'Ashwagandha Root Powder', 'herbs', 'ingredient', 1700, 'Ground Ayurvedic root for warm, grounding preparations.', 'Fine ashwagandha root powder with preparation ideas and safety guidance.', 'active'),
  ('blue-lotus-flower', 'Blue Lotus Flowers', 'flowers', 'ingredient', 2200, 'Dried blue water lily flowers for contemplative practice.', 'Verified dried blue water lily flowers with historical and contemporary context.', 'active'),
  ('palo-santo-wood', 'Ethically Sourced Palo Santo', 'herbs', 'ingredient', 1500, 'Naturally fallen aromatic wood with sourcing notes.', 'Traceable palo santo sourced from naturally fallen material.', 'active'),
  ('calendula-flowers', 'Calendula Flowers', 'flowers', 'ingredient', 1200, 'Golden whole flowers for oil infusions and botanical craft.', 'Fully dried calendula flowers for skin-safe oil infusions, bath blends, and craft.', 'active'),
  ('black-cohosh-root', 'Black Cohosh Root', 'herbs', 'ingredient', 1900, 'Practitioner-guided root with detailed safety notes.', 'Cut black cohosh root for informed study and practitioner-guided use.', 'active')
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  type = excluded.type,
  price_cents = excluded.price_cents,
  short = excluded.short,
  description = excluded.description,
  status = excluded.status,
  updated_at = now();

create table if not exists public.book_of_roots (
  id bigint generated by default as identity primary key,
  name text not null unique,
  image_url text,
  traditions text[] not null default '{}',
  purposes text[] not null default '{}',
  ingredient_type text not null check (ingredient_type in ('Herbs', 'Roots', 'Flowers', 'Oils', 'Resins', 'Bark')),
  description text not null,
  how_to_use text not null,
  product_id bigint references public.products(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists book_of_roots_product_id_idx on public.book_of_roots(product_id);

alter table public.book_of_roots enable row level security;

create policy "Book of Roots entries are public"
on public.book_of_roots
for select
using (true);

create policy "Service role can manage Book of Roots"
on public.book_of_roots
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

insert into public.book_of_roots
  (name, traditions, purposes, ingredient_type, description, how_to_use, product_id)
select seed.name, seed.traditions, seed.purposes, seed.ingredient_type, seed.description,
       seed.how_to_use, products.id
from (
  values
    ('Mugwort', array['Wicca','Native American'], array['Sleep','Protection','Spiritual Growth'], 'Herbs', 'A dream herb in European practice and in distinct Indigenous plant traditions; specific teachings belong to the communities that preserve them.', 'Place dried mugwort in a sachet near the pillow and record dreams on waking. Avoid during pregnancy and check medication interactions.', 'mugwort-dream-herb'),
    ('Dragon''s Blood Resin', array['Santeria','Voodoo'], array['Protection','Cleansing'], 'Resins', 'A red plant resin with histories in incense, dye, and protective folk practices; meaning varies by region and spiritual house.', 'Warm a pinch on charcoal in a fireproof burner with good ventilation. Never leave burning resin unattended.', 'dragons-blood-resin'),
    ('Rose Petals', array['Islamic Tibb','Wicca'], array['Love & Attraction','Cleansing','Healing'], 'Flowers', 'Rose carries rich histories in perfumery, devotional poetry, hospitality, and traditional wellness systems.', 'Steep food-grade petals for ten minutes, strain, cool, and add to a bath or linen spray. Patch-test topical preparations.', 'rose-petals'),
    ('Rue', array['Santeria','Hoodoo'], array['Protection','Curse Breaking','Cleansing'], 'Herbs', 'Rue is associated with protection in Mediterranean, African-diasporic, and Latin American folk practices.', 'Tie dried rue in a small altar or doorway bundle. Do not ingest; avoid during pregnancy and wear gloves with fresh rue.', 'rue-protection-herb'),
    ('Frankincense', array['Islamic Tibb','Folk Christianity','Rastafari'], array['Spiritual Growth','Cleansing','Protection'], 'Resins', 'Boswellia resin has moved through East African, Arabian, Islamic, and Christian trade and devotional life for millennia.', 'Warm one or two tears in a fireproof burner during prayer or meditation and ventilate the room.', 'frankincense-resin'),
    ('Valerian Root', array['Folk Medicine','Ayurveda'], array['Sleep','Healing'], 'Roots', 'Valerian has a long European folk history as an evening herb, while related species appear in South Asian traditions.', 'Steep one teaspoon of cut root in a covered cup for ten to fifteen minutes. Do not combine with alcohol or sedatives.', 'valerian-root'),
    ('John the Conqueror Root', array['Hoodoo'], array['Protection','Spiritual Growth'], 'Roots', 'High John root holds a celebrated place in Hoodoo and is associated with resilience, luck, and personal power.', 'Carry a whole root in a dedicated mojo bag and learn preparation customs from reputable Hoodoo educators.', 'john-the-conqueror-root'),
    ('Ashwagandha', array['Ayurveda'], array['Healing','Spiritual Growth','Sleep'], 'Roots', 'Ashwagandha is a foundational rasayana in Ayurveda, traditionally used within individualized systems of daily practice.', 'Stir a small amount into warm milk. Consult a clinician about pregnancy, thyroid or autoimmune conditions, and medication.', 'ashwagandha-root'),
    ('Blue Lotus', array['Egyptian','Rastafari'], array['Spiritual Growth','Sleep'], 'Flowers', 'The blue water lily appears in ancient Egyptian art; many present-day spiritual uses are contemporary interpretations.', 'Float petals in a meditation bowl, or use verified food-grade material for a mild tea after checking local rules.', 'blue-lotus-flower'),
    ('Palo Santo', array['Indigenous South American','Folk Medicine'], array['Cleansing','Protection'], 'Bark', 'Palo santo is used in regional South American practices; ethical use requires attention to ecology, species, and living cultures.', 'Briefly light responsibly sourced fallen wood in a fireproof dish, extinguish it fully, and ventilate the space.', 'palo-santo-wood'),
    ('Calendula', array['Folk Medicine','Wicca'], array['Healing','Love & Attraction'], 'Flowers', 'Calendula has a broad European folk history in skin preparations, seasonal observance, and household gardens.', 'Infuse fully dried petals in carrier oil, strain, and patch-test. Avoid use if sensitive to daisy-family plants.', 'calendula-flowers'),
    ('Black Cohosh', array['Native American'], array['Healing','Fertility'], 'Roots', 'Black cohosh is native to eastern North America and has distinct histories of use among several Indigenous nations.', 'Use only with qualified practitioner guidance, especially for liver, pregnancy, hormone, or medication concerns.', 'black-cohosh-root')
) as seed(name, traditions, purposes, ingredient_type, description, how_to_use, product_slug)
join public.products on products.slug = seed.product_slug
on conflict (name) do update set
  traditions = excluded.traditions,
  purposes = excluded.purposes,
  ingredient_type = excluded.ingredient_type,
  description = excluded.description,
  how_to_use = excluded.how_to_use,
  product_id = excluded.product_id;

alter table public.products add column if not exists cj_product_id text;
alter table public.products add column if not exists cj_variant_id text;

alter table public.orders add column if not exists cj_order_id text;
alter table public.orders add column if not exists fulfillment_status text not null default 'manual';
alter table public.orders add column if not exists marketing_link_code text;
alter table public.orders add column if not exists shipping_name text;
alter table public.orders add column if not exists shipping_address jsonb;

create table if not exists public.profiles (
  id uuid primary key,
  email text not null unique,
  full_name text,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'marketing', 'it_coordinator', 'admin', 'president')),
  referral_code text unique,
  rupees integer not null default 0,
  referred_by uuid references public.profiles(id),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.referral_events (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.profiles(id),
  referred_id uuid not null references public.profiles(id),
  event_type text not null check (event_type in ('signup', 'purchase')),
  rupees_awarded integer not null default 0,
  created_at timestamptz not null default now(),
  unique (referrer_id, referred_id, event_type)
);

create table if not exists public.marketing_links (
  id bigint generated by default as identity primary key,
  employee_id uuid references public.profiles(id),
  employee_name text not null,
  link_code text not null unique,
  clicks integer not null default 0,
  conversions integer not null default 0,
  revenue_generated numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.office_tab_access (
  id bigint generated by default as identity primary key,
  user_email text not null,
  tab_id text not null,
  granted_by text,
  created_at timestamptz not null default now(),
  unique (user_email, tab_id)
);

create table if not exists public.site_announcements (
  id bigint primary key default 1 check (id = 1),
  message text not null default '',
  active boolean not null default false,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_email text,
  action_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.referral_events enable row level security;
alter table public.marketing_links enable row level security;
alter table public.office_tab_access enable row level security;
alter table public.site_announcements enable row level security;
alter table public.audit_log enable row level security;

drop policy if exists "Service role can manage profiles" on public.profiles;
drop policy if exists "Service role can manage referral events" on public.referral_events;
drop policy if exists "Service role can manage marketing links" on public.marketing_links;
drop policy if exists "Service role can manage office access" on public.office_tab_access;
drop policy if exists "Service role can manage announcements" on public.site_announcements;
drop policy if exists "Service role can manage audit log" on public.audit_log;

create policy "Service role can manage profiles" on public.profiles for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage referral events" on public.referral_events for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage marketing links" on public.marketing_links for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage office access" on public.office_tab_access for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage announcements" on public.site_announcements for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage audit log" on public.audit_log for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

insert into public.site_announcements (id, message, active)
values (1, '', false)
on conflict (id) do nothing;

alter table public.products add column if not exists uses text[] not null default '{}';
alter table public.products add column if not exists ingredients text[] not null default '{}';
alter table public.products add column if not exists badge text;
alter table public.products add column if not exists format text;

create table if not exists public.nightbloom_pdfs (
  id bigint generated by default as identity primary key,
  title text not null,
  blurb text not null default '',
  pdf_url text not null,
  cover_image_url text,
  price_cents integer not null default 0,
  status text not null default 'active' check (status in ('active', 'draft', 'archived')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.nightbloom_pdfs enable row level security;

drop policy if exists "Active Nightbloom PDFs are public" on public.nightbloom_pdfs;
drop policy if exists "Service role can manage Nightbloom PDFs" on public.nightbloom_pdfs;

create policy "Active Nightbloom PDFs are public"
on public.nightbloom_pdfs
for select
using (status = 'active');

create policy "Service role can manage Nightbloom PDFs"
on public.nightbloom_pdfs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

-- Night Bloom PDF purchases: one row per buyer per unlocked PDF.
create table if not exists public.pdf_purchases (
  id bigint generated by default as identity primary key,
  pdf_id bigint not null references public.nightbloom_pdfs (id) on delete cascade,
  buyer_email text not null,
  stripe_checkout_session_id text,
  amount_cents integer not null default 0,
  created_at timestamptz not null default now(),
  unique (pdf_id, buyer_email)
);

create index if not exists pdf_purchases_buyer_email_idx on public.pdf_purchases (buyer_email);

alter table public.pdf_purchases enable row level security;

drop policy if exists "Service role can manage PDF purchases" on public.pdf_purchases;

create policy "Service role can manage PDF purchases"
on public.pdf_purchases
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');

-- Guild (careers) applications submitted from the public Careers page.
create table if not exists public.guild_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  job_id text,
  job_title text,
  portfolio_url text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'reviewing', 'contacted', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guild_applications_status_idx on public.guild_applications (status);

alter table public.guild_applications enable row level security;

drop policy if exists "Service role can manage guild applications" on public.guild_applications;

create policy "Service role can manage guild applications"
on public.guild_applications
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
