alter table products add column if not exists cj_product_id text;
alter table products add column if not exists cj_variant_id text;

alter table orders add column if not exists cj_order_id text;
alter table orders add column if not exists fulfillment_status text not null default 'manual';
alter table orders add column if not exists marketing_link_code text;
alter table orders add column if not exists shipping_name text;
alter table orders add column if not exists shipping_address jsonb;

create table if not exists profiles (
  id uuid primary key,
  email text not null unique,
  full_name text,
  avatar_url text,
  avatar_url text,
  role text not null default 'user' check (role in ('user', 'marketing', 'it_coordinator', 'admin', 'president')),
  referral_code text unique,
  rupees integer not null default 0,
  referred_by uuid references profiles(id),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists referral_events (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references profiles(id),
  referred_id uuid not null references profiles(id),
  event_type text not null check (event_type in ('signup', 'purchase')),
  rupees_awarded integer not null default 0,
  created_at timestamptz not null default now(),
  unique (referrer_id, referred_id, event_type)
);

create table if not exists marketing_links (
  id bigint generated by default as identity primary key,
  employee_id uuid references profiles(id),
  employee_name text not null,
  link_code text not null unique,
  clicks integer not null default 0,
  conversions integer not null default 0,
  revenue_generated numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists office_tab_access (
  id bigint generated by default as identity primary key,
  user_email text not null,
  tab_id text not null,
  granted_by text,
  created_at timestamptz not null default now(),
  unique (user_email, tab_id)
);

create table if not exists site_announcements (
  id bigint primary key default 1 check (id = 1),
  message text not null default '',
  active boolean not null default false,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  user_email text,
  action_type text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table profiles enable row level security;
alter table referral_events enable row level security;
alter table marketing_links enable row level security;
alter table office_tab_access enable row level security;
alter table site_announcements enable row level security;
alter table audit_log enable row level security;

drop policy if exists "Service role can manage profiles" on profiles;
drop policy if exists "Service role can manage referral events" on referral_events;
drop policy if exists "Service role can manage marketing links" on marketing_links;
drop policy if exists "Service role can manage office access" on office_tab_access;
drop policy if exists "Service role can manage announcements" on site_announcements;
drop policy if exists "Service role can manage audit log" on audit_log;

create policy "Service role can manage profiles" on profiles for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage referral events" on referral_events for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage marketing links" on marketing_links for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage office access" on office_tab_access for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage announcements" on site_announcements for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage audit log" on audit_log for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');

insert into site_announcements (id, message, active)
values (1, '', false)
on conflict (id) do nothing;
