alter table products add column if not exists uses text[] not null default '{}';
alter table products add column if not exists ingredients text[] not null default '{}';
alter table products add column if not exists badge text;
alter table products add column if not exists format text;

create table if not exists nightbloom_pdfs (
  id bigint generated by default as identity primary key,
  title text not null,
  blurb text not null default '',
  pdf_url text not null,
  cover_image_url text,
  price_cents integer not null default 0,
  status text not null default 'active' check (status in ('active', 'draft', 'archived')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table nightbloom_pdfs enable row level security;

drop policy if exists "Active Nightbloom PDFs are public" on nightbloom_pdfs;
drop policy if exists "Service role can manage Nightbloom PDFs" on nightbloom_pdfs;

create policy "Active Nightbloom PDFs are public"
on nightbloom_pdfs
for select
using (status = 'active');

create policy "Service role can manage Nightbloom PDFs"
on nightbloom_pdfs
for all
using (auth.role() = 'service_role')
with check (auth.role() = 'service_role');
