-- President's Office: announcement audience, user moderation, analytics, audit documents.

-- 1. Announcement audience targeting (site-wide vs employees only).
alter table public.site_announcements
  add column if not exists audience text not null default 'site';

alter table public.site_announcements
  drop constraint if exists site_announcements_audience_check;

alter table public.site_announcements
  add constraint site_announcements_audience_check
  check (audience in ('site', 'employees'));

-- 2. User moderation: block users and record their last seen IP.
alter table public.profiles
  add column if not exists blocked boolean not null default false;

alter table public.profiles
  add column if not exists last_ip text;

-- 3. IP banning.
create table if not exists public.banned_ips (
  id bigint generated by default as identity primary key,
  ip_address text not null unique,
  reason text,
  created_by text,
  created_at timestamptz not null default now()
);

-- 4. Network analytics: lightweight page-view tracking.
create table if not exists public.page_views (
  id bigint generated by default as identity primary key,
  path text not null,
  referrer text,
  source text,
  ip_address text,
  user_email text,
  user_agent text,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx on public.page_views (created_at desc);
create index if not exists page_views_source_idx on public.page_views (source);

-- 5. Audit documents uploaded by the President / high command.
create table if not exists public.audit_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  file_url text not null,
  uploaded_by text,
  created_at timestamptz not null default now()
);

-- 6. Row Level Security (server uses the service role, public app never touches these directly).
alter table public.banned_ips enable row level security;
alter table public.page_views enable row level security;
alter table public.audit_documents enable row level security;

drop policy if exists "Service role can manage banned ips" on public.banned_ips;
drop policy if exists "Service role can manage page views" on public.page_views;
drop policy if exists "Service role can manage audit documents" on public.audit_documents;

create policy "Service role can manage banned ips" on public.banned_ips
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage page views" on public.page_views
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage audit documents" on public.audit_documents
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
