-- Night Bloom digital sales (purchase-gated PDF downloads) + Join the Guild applications.

-- 1. Night Bloom PDF purchases: one unlock per buyer per PDF.
create table if not exists public.pdf_purchases (
  id bigint generated by default as identity primary key,
  pdf_id bigint not null references public.nightbloom_pdfs (id) on delete cascade,
  buyer_email text not null,
  stripe_checkout_session_id text,
  amount_cents integer not null default 0,
  created_at timestamptz not null default now(),
  unique (pdf_id, buyer_email)
);

create index if not exists pdf_purchases_buyer_email_idx on public.pdf_purchases (buyer_email);
create index if not exists pdf_purchases_pdf_id_idx on public.pdf_purchases (pdf_id);

-- 2. Guild (careers) applications submitted from the public Join the Guild form.
create table if not exists public.guild_applications (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  job_id text,
  job_title text,
  portfolio_url text,
  message text not null,
  status text not null default 'new' check (status in ('new', 'reviewing', 'contacted', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists guild_applications_status_idx on public.guild_applications (status);
create index if not exists guild_applications_created_at_idx on public.guild_applications (created_at desc);

-- 3. Row Level Security: the server uses the service role; the public app never touches these directly.
alter table public.pdf_purchases enable row level security;
alter table public.guild_applications enable row level security;

drop policy if exists "Service role can manage pdf purchases" on public.pdf_purchases;
drop policy if exists "Service role can manage guild applications" on public.guild_applications;

create policy "Service role can manage pdf purchases" on public.pdf_purchases
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
create policy "Service role can manage guild applications" on public.guild_applications
  for all using (auth.role() = 'service_role') with check (auth.role() = 'service_role');
