/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as OracleRouteImport } from './routes/oracle'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as NightbloomRouteImport } from './routes/nightbloom'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BookOfRootsRouteImport } from './routes/book-of-roots'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const OracleRoute = OracleRouteImport.update({
  id: '/oracle',
  path: '/oracle',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const NightbloomRoute = NightbloomRouteImport.update({
  id: '/nightbloom',
  path: '/nightbloom',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BookOfRootsRoute = BookOfRootsRouteImport.update({
  id: '/book-of-roots',
  path: '/book-of-roots',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/book-of-roots': typeof BookOfRootsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/join': typeof JoinRoute
  '/nightbloom': typeof NightbloomRoute
  '/office': typeof OfficeRoute
  '/oracle': typeof OracleRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/book-of-roots': typeof BookOfRootsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/join': typeof JoinRoute
  '/nightbloom': typeof NightbloomRoute
  '/office': typeof OfficeRoute
  '/oracle': typeof OracleRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/book-of-roots': typeof BookOfRootsRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/join': typeof JoinRoute
  '/nightbloom': typeof NightbloomRoute
  '/office': typeof OfficeRoute
  '/oracle': typeof OracleRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/book-of-roots'
    | '/careers'
    | '/cart'
    | '/join'
    | '/nightbloom'
    | '/office'
    | '/oracle'
    | '/shop'
    | '/signin'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/book-of-roots'
    | '/careers'
    | '/cart'
    | '/join'
    | '/nightbloom'
    | '/office'
    | '/oracle'
    | '/shop'
    | '/signin'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/book-of-roots'
    | '/careers'
    | '/cart'
    | '/join'
    | '/nightbloom'
    | '/office'
    | '/oracle'
    | '/shop'
    | '/signin'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  BookOfRootsRoute: typeof BookOfRootsRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  JoinRoute: typeof JoinRoute
  NightbloomRoute: typeof NightbloomRoute
  OfficeRoute: typeof OfficeRoute
  OracleRoute: typeof OracleRoute
  ShopRoute: typeof ShopRoute
  SigninRoute: typeof SigninRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oracle': {
      id: '/oracle'
      path: '/oracle'
      fullPath: '/oracle'
      preLoaderRoute: typeof OracleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nightbloom': {
      id: '/nightbloom'
      path: '/nightbloom'
      fullPath: '/nightbloom'
      preLoaderRoute: typeof NightbloomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-of-roots': {
      id: '/book-of-roots'
      path: '/book-of-roots'
      fullPath: '/book-of-roots'
      preLoaderRoute: typeof BookOfRootsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  BookOfRootsRoute: BookOfRootsRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  JoinRoute: JoinRoute,
  NightbloomRoute: NightbloomRoute,
  OfficeRoute: OfficeRoute,
  OracleRoute: OracleRoute,
  ShopRoute: ShopRoute,
  SigninRoute: SigninRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
